apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployement
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: microserviceuser
          image: ihd99/microserviceuser
          ports:
            - containerPort: 4000 